name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix: 
        dotnet: ["7.0.0"]

    steps:
      - uses: actions/checkout@v2
      - name: Print dotnet version
        run: echo Dotnet version is ${{ matrix.dotnet }}
      - name: Setup .NET Core SDK ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o /var/www/anime-figures.moe
